### ISSUE TITLE
Question on underscore behaviour

### ISSUE THREAD

**Issue by nico202** [korsbo/Latexify.jl#103]
Hi, I usually name functions like: `ω_max`

Latexify is exporting it as ω\_{m}ax, where I think it should place in underscript all the word.  Thoughts?

Thanks, Nicolò

**Comment by korsbo** [comment]
Tricky one... `\omega_max` seems like a terribly poor default but I hesitate to whether the underscores should be kept or whether they should signify subscripts. In your example, subscript seems like a good idea but for functions like `get_some_quantity()` it could make more sense to try to make the function name look more like code than maths. 

I'm not sure what the default should be, but this printout should at least be configurable. 

Configurability is a deeper issue that Latexify has at the moment. It would be easy to add another kwarg, but I think that that is already getting a bit out of hand. I'm planning on overhauling the way that users can configure the output in general and this should be part of that overhaul. It will, however, have to wait at least until autumn since I'm currently swamped with my PhD, new job, moving countries, kids, buying a house, etc.

**Comment by nico202** [comment]
Yeah you are right about `get_some_quantity`.  If I have some idea I'll open a PR

Thanks! Nicolò

**Comment by gustaphe** [comment]
Closed with #219
