### ISSUE TITLE
Add an option to use commas instead of points as decimal separators

### ISSUE THREAD

**Issue by ghralima** [korsbo/Latexify.jl#180]
I'd like to ask for an option to use commas instead of points as decimal separators when using number formatting numbers with latexify.

**Comment by gustaphe** [comment]
If you're interacting with actual LaTeX (i.e. not done html context), a workaround is to use UnitfulLatexify and write `latexify(1.23u"one", unitformat=:siunitx)`. That way you leave the typesetting to siunitx and can use `\sisetup{output-decimal-marker = {,}}` in the main LaTeX file.

**Comment by ghralima** [comment]
Actually, my use is in notebooks (Pluto or Jupyter). Latexify is very useful, but as most of the time, I'm writing in portuguese, I have to use latexstrings instead of latexify to replace "." for ",".

**Comment by korsbo** [comment]
hmm, Latexify outsources most of the conversion of numbers to strings to `Base` in one way or another. You can, however, get something like what you want by using `Base.replace`. The naive way to get what you want might be to just do

```julia
using Latexify
lstr = latexify([1.1, 2.2])
lstr = replace(lstr, '.'=>',')
```
which will simply replace all `.` in your string with `,` but it will not do anything fancy if you happen to use a number formatter that uses commas to indicate thousands `1,000,000.0`. 

you could also build your own little number formatter and pass to latexify...

```julia
julia> fmt(x) = replace(string(x), '.'=>',')
fmt (generic function with 1 method)

julia> latexify(128329.12894; fmt=fmt)
L"$128329,12894$"
```

This could be combined with `Latexify.set_default` so that you only have to specify this at the first cell of your notebook. It could also be combined with the number formatters like
```julia
julia> fmt(x) = replace(FancyNumberFormatter(2)(x), '.'=>',')
fmt (generic function with 1 method)

julia> latexify(128329.12894; fmt=fmt)
L"$1,3 \cdot 10^{5}$"
```

**Comment by ghralima** [comment]
This solves my problem. Just a small comment to people who might find this useful. Actually you have to use: 

```julia
julia > fmt(x) = replace(string(x), '.'=>"{,}")
```
with the comma between the curly brackets, otherwise you will have a small space after the comma in your number.

Thanks for the help!
