### ISSUE TITLE
Doesn't translate accents

### ISSUE THREAD

**Issue by BeastyBlacksmith** [korsbo/Latexify.jl#182]
```julia
julia> latexify("ç")
L"$ç$"

julia> latexify("ã")
L"$ã$"
```
should become

```julia
julia> latexify("ç")
L"\c{c}"

julia> latexify("ã")
L"\~{a}"
```

I'd say.

**Comment by korsbo** [comment]
Hmmm, it seems like the massive unicode -> latex dict in `src/unicode2latex.jl` is incomplete. That's a bit troubling since I have no desire to manually curate such a mapping. Any individual mappings could easily be PRd by just adding entries, but the deeper problem is why there are any such mappings missed at all.
