### ISSUE TITLE
Pluto & Latexify

### ISSUE THREAD

**Issue by oviedorodolfo** [korsbo/Latexify.jl#217]
Hi,
Reference is made to the following paragraph in the documentation: "And when this LaTeXString is displayed in an environment which supports the tex/latex MIME type (Jupyter notebooks, Jupyterlab and Hydrogen for Atom) it will automatically render as:"
Can Pluto.jl use Latexify.jl?
Thanks,
Rodolfo

**Comment by gustaphe** [comment]
Hi!

Yes! There's a couple of different things you can do:

`latexify(x)` in a cell by itself will show the latexification of `x`.

```
@latexify x^2 - 2x
```
will show that expression as latex. 

Because of an annoying visual bug (see if you can spot it), `@latexrun` and `@latexdefine` work best when enclosed in a begin/end:
```
begin
    @latexdefine y = 13x
end
```

And finally a very nice bit of workflow is to use `Markdown.parse` (sadly won't work with `md"" ` syntax):

```
Markdown.parse("""
The measured length is $(@latexdefine x), which is very long.
""")
```

**Comment by oviedorodolfo** [comment]
Thank you, Gustaphe, for your clear explanation!
Would you like to add Pluto to the referred paragraph of the documentation or should I do this?

**Comment by gustaphe** [comment]
If you make a PR, I'll be happy to merge it. Thank you :)

**Comment by gustaphe** [comment]
By the way, I found another way to avoid the visual bug without `begin/end`:

```julia
@latexrun (a,) = b
```
