### ISSUE TITLE
Is there a neat way to generate Euler's formula $e^{\pi i} =1$ with latexify?

### ISSUE THREAD

**Issue by frankhuettner** [korsbo/Latexify.jl#31]
Perhaps this would be a neat example for the documentation.

**Comment by korsbo** [comment]
Hi Frank,

There is, but with a caveat (assignments are sometimes tricky).

Both of these examples will work:
```julia
latexify(:(1=e^(π*i)))
latexify("1=e^(π*i)")
```

However, if you reverse the left-hand-side and the right, it will not work. One can see why that is by inspecting the expression object that is being created in the two cases:

```julia
Julia> ex = :(1 = e^(π*i))
Julia> ex.args
2-element Array{Any,1}:
 1              
  :(e ^ (π * i))
```

```julia
Julia> ex2 = :(e^(π*i) = 1)
Julia> ex2.args
2-element Array{Any,1}:
 :(e ^ (π * i))                     
 quote
    #= In[212]:1 =#
    1
end
```

The problem here boils down to our statement not actually being valid Julia code (what should Julia do with the `e^(π*i) = 1` line?). 

In the first case, Julia is preparing an expression for variable assignment, but in the second, the expression structure is more like a function definition. 

I could make a hacky fix for this which just parsed the second line of the quote block, but such hacky solutions often lead to later headaches. For now I'm pretty content with limiting Latexify to work with valid Julia code and just say that the latter case is outside the scope of the package.

**Comment by korsbo** [comment]
Perhaps I should mention something to this effect in the documentation, and after that I could close the issue.
