### ISSUE TITLE
Latex output for macros ignores recipes

### ISSUE THREAD

**Issue by superyuuki** [korsbo/Latexify.jl#314]
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/766f571a-9762-4571-a8ff-d79b29efe88a">

**Comment by gustaphe** [comment]
This is because `@latexify MyDifference(2,1)` does not evaluate the function `MyDifference()`, but is equivalent to `latexify(:(MyDifference(2,1)))` or `latexify(Expr(:call, :MyDifference, 2, 1)))`. This is a feature, we don't want `@latexify a + b` to evaluate `a + b`.

To get around this, use `@latexify $(MyDifference(2,1))`.

**Comment by superyuuki** [comment]
That makes sense, thank you!
