### ISSUE TITLE
Documentation is not updating upon releases.

### ISSUE THREAD

**Issue by korsbo** [korsbo/Latexify.jl#98]
The last few releases are not visible in the docs. Probably some change to Documenter.jl.

**Comment by moustachio-belvedere** [comment]
Hi Niklas. Hope you're well. I was struggling with that last week on our repository. I had a look at your TagBot action workflow and your travis.yml file and it looks like it may be caused by the same issue as ours. There is more discussion here:

https://discourse.julialang.org/t/how-to-get-documenter-to-recognize-new-release/37111

It seems that either you need to add the tag regular expression on your travis CI config file to make sure it is triggered on tag pushing (what we did), or link your workflow to a specific SSH key (didn't try this way.) You can re-use the documenter key you used for Travis (the private key you gave to Travis previously needs to be added as a Github secret as well). Our final working travis config file is here:

https://github.com/JuliaRheology/RHEOS.jl/blob/master/.travis.yml

and a github action file I was testing out (seems to work succesfully) on a dummy test package I was trying over the weekend is here:

https://github.com/moustachio-belvedere/JuliaPackageDemo.jl/blob/master/.github/workflows/documentbuild.yml
